{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{ if .Values.pachd.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.pachd.storage.google.serviceAccountName }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.pachd.storage.google.serviceAccountName | quote }}
  {{- end }}
  labels:
    app: ""
    suite: pachyderm
  name: {{ .Values.pachd.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace }}
{{ end }}
