{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ""
    suite: pachyderm
  name: pachyderm-worker
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ""
  kind: Role
  name: pachyderm-worker
subjects:
- kind: ServiceAccount
  name: {{ .Values.pachd.workerServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}