{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{ if and .Values.worker.serviceAccount.create .Values.pachd.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.pachd.storage.google.serviceAccountName }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.pachd.storage.google.serviceAccountName | quote }}
  {{- end }}
  {{- if .Values.worker.serviceAccount.additionalAnnotations }}
  annotations: {{ toYaml .Values.worker.serviceAccount.additionalAnnotations | nindent 3 }}
  {{- end }}
  labels:
    app: ""
    suite: pachyderm
  name: {{ .Values.worker.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{ end }}
