{{- if .Values.dash.url -}}
apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
  name: "dash"
  annotations:
    kubernetes.io/ingress.class: "traefik"
  labels:
    app: "dash"
    suite: "pachyderm"
spec:
  {{- if .Values.dash.tls.enabled }}
  tls:
    - secretName: {{ required "if dash.tls.enabled you must specify dash.tls.secretName" .Values.dash.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.dash.url | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "dash"
              servicePort: "dash-http"
          - path: "/ws"
            backend:
              serviceName: "dash"
              servicePort: "grpc-proxy-http"
{{ end -}}
