---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dash
    suite: pachyderm
  name: dash
spec:
  ports:
  - name: dash-http
    port: 8080
  - name: grpc-proxy-http
    port: 8081
  selector:
    app: dash
    suite: pachyderm
  type: ClusterIP
