---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd-headless
spec:
  clusterIP: None
  ports:
  - name: peer-port
    port: 2380
  selector:
    app: etcd
