{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if le .Values.etcd.dynamicNodes 0.0 -}}
{{ fail "dynamicNodes must be > 0" }}
{{ end -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.etcd.dynamicNodes }}
  selector:
    matchLabels:
      app: etcd
      suite: pachyderm
  serviceName: etcd-headless
  template:
    metadata:
      labels:
        app: etcd
        suite: pachyderm
      name: etcd
      namespace: {{ .Release.Namespace }}
    spec:
      containers:
      - args:
        - '"/usr/local/bin/etcd" "--listen-client-urls=http://0.0.0.0:2379" "--advertise-client-urls=http://0.0.0.0:2379"
          "--data-dir=/var/data/etcd" "--auto-compaction-retention=1" "--max-txn-ops=10000"
          "--max-request-bytes=52428800" "--quota-backend-bytes=8589934592" "--listen-peer-urls=http://0.0.0.0:2380"
          "--initial-cluster-token=pach-cluster" "--initial-advertise-peer-urls=http://${ETCD_NAME}.etcd-headless.${NAMESPACE}.svc.cluster.local:2380"
          "--initial-cluster={{ range $i, $e := until (.Values.etcd.dynamicNodes | int) }}etcd-{{$e}}=http://etcd-{{$e}}.etcd-headless.${NAMESPACE}.svc.cluster.local:2380{{ end }}"'
        command:
        - /bin/sh
        - -c
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: "{{ .Values.etcd.image.repository }}:{{ .Values.etcd.image.tag }}"
        imagePullPolicy: {{ .Values.etcd.image.pullPolicy }}
        {{- if .Values.imagePullSecret }}
        imagePullSecret: {{ .Values.imagePullSecret | quote }}
        {{- end }}
        name: etcd
        ports:
        - containerPort: 2379
          name: client-port
        - containerPort: 2380
          name: peer-port
        {{- if .Values.etcd.resources }}
        resources: {{ toYaml .Values.etcd.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/data/etcd
          name: etcd-storage
      {{- if eq .Values.pachd.storage.backend "LOCAL" }}
      volumes:
      - hostPath:
          path: /var/pachyderm/etcd
          type: DirectoryOrCreate
        name: etcd-storage
      {{- end }}
  {{- if not (eq .Values.pachd.storage.backend "LOCAL") }}
  volumeClaimTemplates:
  - metadata:
  {{- if or (eq .Values.pachd.storage.backend "AMAZON") (eq .Values.pachd.storage.backend "GOOGLE") }}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ if .Values.etcd.storageClass -}}
        {{ .Values.etcd.storageClass }}
        {{- else -}}
        etcd-storage-class
        {{- end }}
  {{- end }}
      labels:
        app: etcd
        suite: pachyderm
      name: etcd-storage
      namespace: {{ .Release.Namespace }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.etcd.storageSize }}
  {{- end }}
