dash:
  image:
    tag: "0.5.58"
  resources: null
  # url may be configured per workspace
  url: "https://dash.test/"

etcd:
  annotations:
    prometheus.io/port: "2379"
    prometheus.io/scrape: "true"
  resources:
    requests:
      cpu: "1"
      memory: 2G
    limits: null
  storageClass: "ssd-storage-class"
  # storageSize may be configured per workspace
  storageSize: "3Gi"

loadBalancer:
  ip: "$PACH_CLUSTER_IP"

pachd:
  blockCacheBytes: "0G"
  exposeDockerSocket: true
  image:
    # tag may be configured per workspace
    tag: "1.12.5"
  lokiLogging: true
  # metricsEndpoint may be configured per Hub instance; it is the
  # hostname of the metrics endpoint
  metricsEndpoint: "metrics.test"
  service:
    type: "ClusterIP"
  storage:
    backend: "GOOGLE"
    google:
      # bucket may be configured per workspace
      bucket: "test-bucket"
      cred: ""
      # serviceAccountName may be configured per workspace
      serviceAccountName: "test-service-account"
    putFileConcurrencyLimit: 10
  resources:
    limits:
      cpu: "1"
      memory: 2G
    requests:
      cpu: "1"
      memory: 2G

tls:
  certName: "dash-tls"
  create: null
