pachd:
  storage:
    backend: LOCAL
  image:
    tag: local
  resources:
    limits:
      cpu: 250m
      memory: 512M
    requests:
      cpu: 250m
      memory: 512M
  service: 
    type: NodePort
  metrics:
    enabled: false
  blockCacheBytes: 256M
  authenticationDisabledForTesting: true
  exposeObjectAPI: true
  exposeDockerSocket: true


dash:
  # resources: {} Doesn't work
  service:
    type: NodePort

worker:
  image:
    tag: local

etcd:
  service:
    type: NodePort