# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0

deployTarget: MINIO

pachd:
  storage:
    minio:
      bucket: "foo"
      endpoint: "https://bar.test/"
      id: "baz"
      secret: "quux"
      secure: "quuux"
      signature: "quuuux"
