{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
    suite: pachyderm
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      suite: pachyderm
  serviceName: postgres-headless
  template:
    metadata:
      labels:
        app: postgres
        suite: pachyderm
      name: postgres
      namespace: default
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: pgc
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        image: postgres:13.0-alpine
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          name: client-port
        resources:
          requests:
            cpu: "1"
            memory: 2G
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgres-storage
        - mountPath: /docker-entrypoint-initdb.d
          name: postgres-init
      imagePullSecrets: null
      volumes:
      - configMap:
          name: postgres-init-cm
        name: postgres-init
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: postgres-storage-class
      labels:
        app: postgres
        suite: pachyderm
      name: postgres-storage
      namespace: default
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
