{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- if and (eq .Values.deployTarget "MICROSOFT") (not .Values.postgresql.storageClass) }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: postgres
    suite: pachyderm
  name: postgresql-storage-class
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
provisioner: kubernetes.io/azure-disk
{{ end -}}
