{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "656"
    prometheus.io/scrape: "true"
  labels:
    app: pachd
    suite: pachyderm
    {{- if .Values.pachd.service.labels }}
    {{- toYaml .Values.pachd.service.labels | nindent 4 }}
    {{- end }}
  name: pachd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  # This must remain first in the list for compatibility with old dash (can't connect when TLS enabled on api-grpc-port)
  # The first port in the list sets the PACHD_SERVICE_PORT variable used by https://github.com/pachyderm/grpc-proxy/blob/master/Dockerfile
  - name: api-grpc-peer
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30653
    port: 653
    {{ else }}
    port: 30653
    {{- end }}
    protocol: TCP
    targetPort: peer-port
  - name: api-grpc-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30650
    port: 650
    {{ else }}
    port: 30650
    {{- end }}
    protocol: TCP
    targetPort: api-grpc-port
  - name: trace-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30651
    port: 651
    {{ else }}
    port: 30651
    {{- end }}
    protocol: TCP
    targetPort: trace-port
  - name: api-http-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30652
    port: 652
    {{ else }}
    port: 30652
    {{- end }}
    protocol: TCP
    targetPort: api-http-port
  - name: saml-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30654
    port: 654
    {{ else }}
    port: 30654
    {{- end }}
    targetPort: saml-port
  - name: oidc-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30657
    port: 657
    {{ else }}
    port: 30657
    {{- end }}
    targetPort: oidc-port
  - name: api-git-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30655
    port: 655
    {{ else }}
    port: 30655
    {{- end }}
    targetPort: api-git-port
  - name: s3gateway-port
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30600
    port: 600
    {{ else }}
    port: 30600
    {{- end }}
    targetPort: s3gateway-port
  - name: prom-metrics
    {{- if eq .Values.pachd.service.type "NodePort" }}
    nodePort: 30656
    {{- end }}
    port: 656
    protocol: TCP
    targetPort: prom-metrics
  selector:
    app: pachd
  type: {{ .Values.pachd.service.type }}
