apiVersion: v1
data:
  {{- if eq .Values.pachd.storage.backend "GOOGLE" }}
  google-bucket: {{ required "Google bucket Required when storage backend GOOGLE" .Values.pachd.storage.google.googleBucket | toString | b64enc }}
  google-cred: {{ .Values.pachd.storage.google.googleCred | toString | b64enc }}
  {{- end -}}
  {{- if eq .Values.pachd.storage.backend "MINIO" }}
  minio-bucket: {{ .Values.pachd.storage.minio.minioBucket | toString | b64enc }}
  minio-endpoint: {{ .Values.pachd.storage.minio.minioEndpoint | toString| b64enc }}
  minio-id: {{ .Values.pachd.storage.minio.minioID | toString| b64enc }}
  minio-secret: {{ .Values.pachd.storage.minio.minioSecret | toString | b64enc }}
  minio-secure: {{ .Values.pachd.storage.minio.minioSecure | toString | b64enc }}
  minio-signature: {{ .Values.pachd.storage.minio.minioSignature | toString | b64enc }}
  {{- end -}}
  {{- if eq .Values.pachd.storage.backend "AMAZON" }}
  amazon-bucket: {{ .Values.pachd.storage.amazon.amazonBucket | toString | b64enc }}
  amazon-distribution: {{ .Values.pachd.storage.amazon.amazonDistribution | toString | b64enc }}
  amazon-id: {{ .Values.pachd.storage.amazon.amazonID | toString | b64enc }}
  amazon-region: {{ .Values.pachd.storage.amazon.amazonRegion | toString | b64enc }}
  amazon-secret: {{ .Values.pachd.storage.amazon.amazonSecret | toString | b64enc }}
  amazon-token: {{ .Values.pachd.storage.amazon.amazonToken | toString | b64enc }}
  custom-endpoint: {{ .Values.pachd.storage.amazon.customEndpoint | toString | b64enc }}
  disable-ssl: {{ .Values.pachd.storage.amazon.disableSSL | toString | b64enc }}
  log-options: {{ .Values.pachd.storage.amazon.logOptions | toString | b64enc }}
  max-upload-parts: {{ .Values.pachd.storage.amazon.maxUploadParts | toString | b64enc }}
  no-verify-ssl: {{ .Values.pachd.storage.amazon.noVerifySSL | toString | b64enc }}
  part-size: {{ .Values.pachd.storage.amazon.partSize | toString | b64enc }}
  retries: {{ .Values.pachd.storage.amazon.retries | toString | b64enc }}
  reverse: {{ .Values.pachd.storage.amazon.reverse | toString | b64enc }}
  timeout: {{ .Values.pachd.storage.amazon.timeout | toString | b64enc }}
  upload-acl: {{ .Values.pachd.storage.amazon.uploadACL | toString | b64enc }}
  {{- end -}}
  {{- if eq .Values.pachd.storage.backend "MICROSOFT" }}
  microsoft-container: {{ .Values.pachd.storage.microsoft.microsoftContainer | toString | b64enc }}
  microsoft-id: {{ .Values.pachd.storage.microsoft.microsoftID | toString | b64enc }}
  microsoft-secret: {{ .Values.pachd.storage.microsoft.microsoftSecret | toString | b64enc }}
  {{- end }}
kind: Secret
metadata:
  labels:
    app: pachyderm-storage-secret
    suite: pachyderm
  name: pachyderm-storage-secret
  namespace: {{ .Release.Namespace }}