apiVersion: v1
data:
  {{- if eq .Values.pachd.storage.backend "GOOGLE" }}
  google-bucket: {{ required "Google bucket Required when storage backend GOOGLE" .Values.pachd.storage.google.googleBucket | b64enc }}
  google-cred: {{ .Values.pachd.storage.google.googleCred | b64enc }}
  {{- end -}}
  {{- if eq .Values.pachd.storage.backend "MINIO" }}
  minio-bucket: {{ .Values.pachd.storage.minio.minioBucket | b64enc }}
  minio-endpoint: {{ .Values.pachd.storage.minio.minioEndpoint | b64enc }}
  minio-id: {{ .Values.pachd.storage.minio.minioID | b64enc }}
  minio-secret: {{ .Values.pachd.storage.minio.minioSecret | b64enc }}
  minio-secure: {{ .Values.pachd.storage.minio.minioSecure | b64enc }}
  minio-signature: {{ .Values.pachd.storage.minio.minioSignature | b64enc }}
  {{- end -}}
  {{- if eq .Values.pachd.storage.backend "AMAZON" }}
  amazon-bucket: {{ .Values.pachd.storage.amazon.amazonBucket | b64enc }}
  amazon-distribution: {{ .Values.pachd.storage.amazon.amazonDistribution | b64enc }}
  amazon-id: {{ .Values.pachd.storage.amazon.amazonID | b64enc }}
  amazon-region: {{ .Values.pachd.storage.amazon.amazonRegion | b64enc }}
  amazon-secret: {{ .Values.pachd.storage.amazon.amazonSecret | b64enc }}
  amazon-token: {{ .Values.pachd.storage.amazon.amazonToken | b64enc }}
  custom-endpoint: {{ .Values.pachd.storage.amazon.customEndpoint | b64enc }}
  disable-ssl: {{ .Values.pachd.storage.amazon.disableSSL | b64enc }}
  log-options: {{ .Values.pachd.storage.amazon.logOptions | b64enc }}
  max-upload-parts: {{ .Values.pachd.storage.amazon.maxUploadParts | b64enc }}
  no-verify-ssl: {{ .Values.pachd.storage.amazon.noVerifySSL | b64enc }}
  part-size: {{ .Values.pachd.storage.amazon.partSize | b64enc }}
  retries: {{ .Values.pachd.storage.amazon.retries | b64enc }}
  reverse: {{ .Values.pachd.storage.amazon.reverse | b64enc }}
  timeout: {{ .Values.pachd.storage.amazon.timeout | b64enc }}
  upload-acl: {{ .Values.pachd.storage.amazon.uploadACL | b64enc }}
  {{- end -}}
  {{- if eq .Values.pachd.storage.backend "MICROSOFT" }}
  microsoft-container: {{ .Values.pachd.storage.microsoft.microsoftContainer | b64enc }}
  microsoft-id: {{ .Values.pachd.storage.microsoft.microsoftID | b64enc }}
  microsoft-secret: {{ .Values.pachd.storage.microsoft.microsoftSecret | b64enc }}
  {{- end }}
kind: Secret
metadata:
  labels:
    app: pachyderm-storage-secret
    suite: pachyderm
  name: pachyderm-storage-secret
  namespace: {{ .Release.Namespace }}