{{- if .Values.tls.create }}
{{- /*
SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
SPDX-License-Identifier: Apache-2.0
*/ -}}
apiVersion: "v1"
data:
  tls.crt: {{ .Values.tls.create.crt | b64enc | quote }}
  tls.key: {{ .Values.tls.create.key | b64enc | quote }}
kind: Secret
metadata:
  labels:
    app: "pachyderm"
    suite: "pachyderm"
  name: {{ .Values.tls.certName | quote }}
{{ end -}}
